server:
  port: 8099

spring:
  application:
    name: manantial-ms-consumer
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost:9092 }
    consumer:
      auto-offset-reset: latest
  data:
    redis:
      host: {REDIS_HOST:localhost}
      port: {REDIS_PORT:6379}
